/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/bmZrvUNsR5f
 */
import { Button } from "@/components/ui/button"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Input } from "@/components/ui/input"
import Volver from "@/components/ui/volver";



export function CrearRenglon() {
  return (
    (
      <div className=" p-4 mx-auto w-full max-w-2xl mt-4">
      <div className="bg-white p-4 rounded-md shadow-md mt-4">
        <h2 className="text-lg font-bold mb-4">Nuevo Renglón</h2>
        <div className="grid grid-cols-2 gap-4">
          <div>
          <label className="block text-sm font-medium mb-1" htmlFor="group-name">
              Renglón Número:
            </label>
            <Input id="group-name" placeholder="021" />
          </div>
          <div>
          <label className="block text-sm font-medium mb-1" htmlFor="group-name">
              Tipo:
            </label>
            <Input id="group-name" placeholder="Temporal" />
          </div>
        </div>
        <div className="mt-4">
          <label className="block text-sm font-medium mb-1" htmlFor="group-name">
            Nombre Renglón Contrato:
          </label>
          <Input id="group-name" placeholder="Por servicios técnicos" />
        </div>
        <div className="mt-4">
          <label className="block text-sm font-medium mb-1" htmlFor="group-description">
            Descripción Renglón:
          </label>
          <textarea
            className="resize-none border rounded-md w-full p-2"
            id="group-description"
            placeholder="El renglón 021, se constituye un contrato de trabajo con el estado en ..."
            rows="4"
          />
        </div>
        <div className="flex justify-around mt-4">
          <Button>Guardar</Button>
          <Volver />
        </div>
      </div>
    </div>
    )
  );
}

