/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/bmZrvUNsR5f
 */
import { Button } from "@/components/ui/button"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Input } from "@/components/ui/input"
import ListaEntidadesEmpresa from "../../entidadempresa/entidades-empresas/lista-entidades-empresa";
import ListaDirecciones from "../../entidadempresa/entidades-empresas/areas-direcciones/lista-direcciones";
import ListaDepartamentos from "../../entidadempresa/entidades-empresas/areas-direcciones/departamento/lista-departamentos";
import ListaPuestos from "../lista-puestos";
import ListaRenglones from "../renglones-presupuestarios/lista-renglones";




export function CrearDireccionVacante() {
  return (
    (
      <div className=" p-4 mx-auto w-full max-w-4xl mt-4">
      <div className="bg-white p-4 rounded-md shadow-md mt-4">
        <h2 className="text-lg font-bold text-[#2c5282] mb-4">Nueva Direccion Web para Registro de Vacante</h2>
        <div className="grid grid-cols-2 gap-4 ">
          <div>
          <ListaPuestos />
          </div>
          <div>
          <label className="block text-sm font-medium mb-1" htmlFor="group-type">
              Tipo de usuario:
            </label>
          <Select>
        <SelectTrigger id="group-type">
          <SelectValue placeholder="Seleccione uno" />
        </SelectTrigger>
        <SelectContent position="popper">
          <SelectItem value="public">Externo - Evaluado</SelectItem>
          <SelectItem value="public">Interno - Usuario</SelectItem>
        </SelectContent>
      </Select>
      </div>
      </div>

      <div className="grid grid-cols-4 gap-4 mt-4 ">
      <label className="block text-sm font-medium" htmlFor="group-type">
              Evaluaciones disponibles:
            </label>
          <div className=" col-start-1 col-end-4">
          <Select>
        <SelectTrigger id="group-type">
          <SelectValue placeholder="Seleccione uno" />
        </SelectTrigger>
        <SelectContent position="popper">
          <SelectItem value="public">Excel 365 - 2023 - Formulas</SelectItem>
        </SelectContent>
      </Select>
      </div>
      <div className="flex justify-center items-center">
          <Button>Asignar</Button>
      </div>

      </div>
      
      <div className="grid grid-cols-1 gap-4 mt-4">
      <div>
          <label className="block text-sm font-medium mb-1" htmlFor="group-type">
              Evaluaciones asignadas:
            </label>
            <div className="rounded-md shadow-md p-2 ">
            <Table>
          <TableHeader>
            <TableRow>
              <TableHead className="w-[100px]">Titulo</TableHead>
              <TableHead className="w-[100px]">Accion</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            <TableRow>
              <TableCell>Procesos Basicos de Contabilidad I</TableCell>
    
              <TableCell>
                <Button variant="ghost">Eliminar</Button>
              </TableCell>
            </TableRow>
          </TableBody>
        </Table>
        </div>
      </div>
      </div>
        
        <div className="mt-4">
          <label className="block text-sm font-medium m-1" htmlFor="group-name">
            Direccion del registro de vacante:
          </label>
          <label className="block text-sm font-medium m-1 text-blue-600" htmlFor="group-name">
            https://www.evaluaciones.com/registro-vacante/123456
          </label>
        </div>
        <div className="flex justify-end mt-4">
          <Button>Guardar</Button>
        </div>
      </div>
    </div>
    )
  );
}


function SignalIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M2 20h.01" />
      <path d="M7 20v-4" />
      <path d="M12 20v-8" />
      <path d="M17 20V8" />
      <path d="M22 4v16" />
    </svg>)
  );
}
