/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/bmZrvUNsR5f
 */
import { Button } from "@/components/ui/button"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Input } from "@/components/ui/input"
import ListaEntidadesEmpresa from "../../subentidades/entidades-empresas/lista-entidades-empresa";
import ListaDirecciones from "../../subentidades/entidades-empresas/areas-direcciones/lista-direcciones";
import ListaDepartamentos from "../../subentidades/entidades-empresas/areas-direcciones/departamento/lista-departamentos";
import ListaPuestos from "../lista-puestos";
import ListaRenglones from "../renglones-presupuestarios/lista-renglones";



export function NuevaVacante() {
  return (
    (
      <div className=" p-4 mx-auto w-full max-w-4xl mt-4">
      <div className="bg-white p-4 rounded-md shadow-md mt-4">
        <h2 className="text-lg font-bold text-[#2c5282] mb-4">Nuevo Vacante</h2>
        <div className="grid grid-cols-5 gap-4 ">
        <div>
          <ListaEntidadesEmpresa />
          </div>
          <div>
          <ListaDirecciones />
          </div>
          <div>
          <ListaDepartamentos />
          </div>
          <div>
          <ListaPuestos />
          </div>
          <div>
           <ListaRenglones />
          </div>
          <div />
        </div>
        <div className="grid grid-cols-2 gap-4">
        <div>
            <label className="block text-sm font-medium mb-1" htmlFor="group-name">
                Vigente del:
                </label>
                <Input id="group-name" placeholder="Date" />
        </div>
        <div>
            <label className="block text-sm font-medium mb-1" htmlFor="group-name">
               Al:
                </label>
                <Input id="group-name" placeholder="Date" />
        </div>
        </div>

        <div className="grid grid-cols-2 gap-4 mt-2">
        <div>
            <label className="block text-sm font-medium mb-1" htmlFor="group-name">
                No. de Plazas Vacantes
                </label>
                <Input id="group-name" placeholder="02s" />
        </div>
        <div>
            <label className="block text-sm font-medium mb-1" htmlFor="group-name">
               Estatus:
                </label>
                <Select>
        <SelectTrigger id="group-type">
          <SelectValue placeholder="Seleccione uno" />
        </SelectTrigger>
        <SelectContent position="popper">
          <SelectItem value="public">Activa - Vigente</SelectItem>
          <SelectItem value="public">Vencida</SelectItem>
          <SelectItem value="public">Cubierta</SelectItem>
          <SelectItem value="public">Cancelada</SelectItem>
        </SelectContent>
      </Select>
        </div>
        </div>
        
        <div>
          <label className="block text-sm font-medium m-1" htmlFor="group-name">
            Nombre Vacante:
          </label>
          <Input id="group-name" placeholder="Auxiliar de Costos" />
        </div>
        <div className="mt-4">
          <label className="block text-sm font-medium mb-1" htmlFor="group-description">
            Descripción General Vacante:
          </label>
          <textarea
            className="resize-none border rounded-md w-full p-2"
            id="group-description"
            placeholder="La vacante ..."
            rows="4"
          />
        </div>
        <div className="flex justify-end mt-4">
          <Button>Guardar</Button>
        </div>
      </div>
    </div>
    )
  );
}


function SignalIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M2 20h.01" />
      <path d="M7 20v-4" />
      <path d="M12 20v-8" />
      <path d="M17 20V8" />
      <path d="M22 4v16" />
    </svg>)
  );
}
