/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/TZ6Ae8jjXO2
 */
import { CardHeader, CardContent, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function RegistroPublico() {
  return (
    (
      <form className="p-8 space-y-8 mt-8 mb-8 mx-auto max-w-7xl">
    <div className="h-fit overflow-hidden">
    <Card className="mx-auto max-w-lg space-y-6">
      <CardHeader>
        <h1 className="text-3xl font-bold">Registro</h1>
        <p className="text-gray-500 dark:text-gray-400">Por favor complete el formulario para crear una cuenta</p>
      </CardHeader>
      <CardContent className="space-y-6">
        <div className="grid grid-cols-2 gap-1">
          <div className="space-y-2">
            <Label htmlFor="first-name">Primer nombre:</Label>
            <Input id="first-name" placeholder="Juan" required />
          </div>
          <div className="space-y-2">
            <Label htmlFor="middle-name">Segundo nombre:</Label>
            <Input id="middle-name" placeholder="Javier" required />
          </div>
          <div className="space-y-2">
            <Label htmlFor="last-name">Apellido paterno</Label>
            <Input id="last-name" placeholder="Diaz" required />
          </div>
          <div className="space-y-2">
            <Label htmlFor="last-name2">Apellido materino:</Label>
            <Input id="last-name2" placeholder="Gomez" required />
          </div>
        </div>
        <div className="space-y-2">
          <Label htmlFor="date-of-birth">Fecha de nacimiento</Label>
          <Input id="date-of-birth" required type="date" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="dpi-cui">DPI/CUI</Label>
          <Input id="dpi-cui" placeholder="1234567891011" required />
        </div>
        <div className="space-y-2">
          <Label htmlFor="country">Pais de origen</Label>
          <Input id="country" placeholder="Guatemala" required />
        </div>
        <div className="space-y-2">
          <Label htmlFor="email">Email</Label>
          <Input id="email" placeholder="example@mail.com" required type="email" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="password">Password</Label>
          <Input id="password" required type="password" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="confirm-password">Confirm Password</Label>
          <Input id="confirm-password" required type="password" />
        </div>
        <Button className="w-full" type="submit">
          Registrarse
        </Button>
      </CardContent>
    </Card>
    </div>
    </form>
    )
  );
}
