/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/bmZrvUNsR5f
 */
import { Button } from "@/components/ui/button"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Input } from "@/components/ui/input"
import ListaEntidades from "../../entidad/lista-entidades";
import ListaGruposcorporativos from "../../gruposcorporativos/lista-gruposcorporativos";

export function NuevasSubEntidadesEmpresas() {
  return (
    (
      <div className=" p-4 mx-auto w-full max-w-2xl mt-4">
      <div className="bg-white p-4 rounded-md shadow-md mt-4">
        <h2 className="text-lg font-bold text-[#2c5282] mb-4">Nuevo Sub Tipo Entidad</h2>
        <div className="grid grid-cols-2 gap-4">
        <div>
          <ListaGruposcorporativos />
        </div>
          <div>

            <ListaEntidades />
          </div>
          

          <div />
        </div>
        <div className="mt-4">
          <label className="block text-sm font-medium mb-1" htmlFor="group-name">
            Nombre Sub-Tipo Entidad:
          </label>
          <Input id="group-name" placeholder="Ministerio de comunicaciones" />
        </div>
        <div className="mt-4">
          <label className="block text-sm font-medium mb-1" htmlFor="group-description">
            Descripción Sub-Tipo Entidad:
          </label>
          <textarea
            className="resize-none border rounded-md w-full p-2"
            id="group-description"
            placeholder="El ministerio de ..."
            rows="4"
          />
        </div>
        <div className="flex justify-end mt-4">
          <Button>Guardar</Button>
        </div>
      </div>
    </div>
    )
  );
}


function SignalIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M2 20h.01" />
      <path d="M7 20v-4" />
      <path d="M12 20v-8" />
      <path d="M17 20V8" />
      <path d="M22 4v16" />
    </svg>)
  );
}
