/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/bmZrvUNsR5f
 */
import { Button } from "@/components/ui/button"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Input } from "@/components/ui/input"

export function NuevosGruposCorporativos() {
  return (
    (<div key="1" className="bg-[#e5e7eb] p-4">
      <div className="bg-white p-4 rounded-md shadow-md">
        <h1 className="text-xl font-bold text-center text-[#2c5282] mb-4">
          MODULO 2-1-1 GRUPOS CORPORATIVOS, TIPOS ENTIDADES Y SUB-TIPOS
        </h1>
        <div className="flex justify-end">
          <Button className="bg-[#e53e3e] text-white">
            VER
            <SignalIcon className="ml-1" />
          </Button>
        </div>
        <div className="overflow-x-auto mt-4">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead className="w-[100px]">Grupo Tipo</TableHead>
                <TableHead className="w-[200px]">Nombre del GRUPO</TableHead>
                <TableHead className="w-[150px]">Fecha Registro</TableHead>
                <TableHead className="w-[150px]">Última Modificación</TableHead>
                <TableHead className="w-[100px]" />
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow>
                <TableCell>Público</TableCell>
                <TableCell>Sector Público – Gobierno – Estatal</TableCell>
                <TableCell>01/11/2023</TableCell>
                <TableCell>28/11/2023</TableCell>
                <TableCell>
                  <Button variant="ghost">Editar</Button>
                </TableCell>
              </TableRow>
              <TableRow>
                <TableCell>Privado</TableCell>
                <TableCell>Sector Privado Empresarial</TableCell>
                <TableCell>01/11/2023</TableCell>
                <TableCell>28/11/2023</TableCell>
                <TableCell>
                  <Button variant="ghost">Editar</Button>
                </TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </div>
        <div className="flex mt-4 space-x-4">
          <Button variant="outline">Reporte</Button>
          <Button variant="outline">Generar PDF</Button>
        </div>
        <div className="flex justify-between items-center mt-4">
          <Button variant="ghost">Regresar</Button>
          <Button>Nuevo GRUPO</Button>
        </div>
      </div>
      <div className="bg-white p-4 rounded-md shadow-md mt-4">
        <h2 className="text-lg font-bold text-[#2c5282] mb-4">NUEVO GRUPO - CORPORACIÓN</h2>
        <div className="grid grid-cols-2 gap-4">
          <div>
            <label className="block text-sm font-medium mb-1" htmlFor="group-type">
              Grupo Tipo Corporativo:
            </label>
            <Select>
              <SelectTrigger id="group-type">
                <SelectValue placeholder="Seleccione uno" />
              </SelectTrigger>
              <SelectContent position="popper">
                <SelectItem value="public">Sector Público</SelectItem>
                <SelectItem value="private">Sector Privado</SelectItem>
                <SelectItem value="ngo">Fideicomisos y Otras Entidades</SelectItem>
                <SelectItem value="international">Organizaciones Internacionales</SelectItem>
                <SelectItem value="other">Otro Tipo</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div />
        </div>
        <div className="mt-4">
          <label className="block text-sm font-medium mb-1" htmlFor="group-name">
            Nombre GRUPO:
          </label>
          <Input id="group-name" placeholder="Especial" />
        </div>
        <div className="mt-4">
          <label className="block text-sm font-medium mb-1" htmlFor="group-description">
            Descripción Grupo:
          </label>
          <textarea
            className="resize-none border rounded-md w-full p-2"
            id="group-description"
            placeholder="El grupo especial..."
            rows="4" />
        </div>
        <div className="flex justify-end mt-4">
          <Button>Guardar</Button>
        </div>
      </div>
    </div>)
  );
}


function SignalIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M2 20h.01" />
      <path d="M7 20v-4" />
      <path d="M12 20v-8" />
      <path d="M17 20V8" />
      <path d="M22 4v16" />
    </svg>)
  );
}
