/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/4tEbnNY55hA
 */
import { SelectValue, SelectTrigger, SelectItem, SelectGroup, SelectContent, Select } from "@/components/ui/select"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import { Checkbox } from "@/components/ui/checkbox"

export function PerfilesUsuario() {
  return (
    (
      <div className="border rounded-lg w-full p-5 m-2 mx-auto m-10 mx-4">
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-lg font-semibold m-2 p-2">Perfil de usuario</h2>
        <div className="m-2 p-2">
          <div>
            <Select>
              <SelectTrigger className="w-[180px] m-2 p-2">
                <SelectValue placeholder="Evaluado (Default)" />
              </SelectTrigger>
              <SelectContent className="m-2 p-2">
                <SelectGroup>
                  <SelectItem className="m-2 p-2" value="Evaluado (Default)">
                    Evaluado (Default)
                  </SelectItem>
                  <SelectItem className="m-2 p-2" value="Option 2">
                    Option 2
                  </SelectItem>
                  <SelectItem className="m-2 p-2" value="Option 3">
                    Option 3
                  </SelectItem>
                </SelectGroup>
              </SelectContent>
            </Select>
          </div>
        </div>
      </div>
      <div className="relative w-full overflow-auto m-2 p-2">
        <h3 className="text-lg font-semibold m-2 p-2">Modulos de sistema</h3>
        <Table>
          <TableHeader className="m-2 p-2">
            <TableRow>
              <TableHead className="w-[200px] m-2 p-2">Seguridad y acceso</TableHead>
              <TableHead className="w-[100px] m-2 p-2">Sin acceso</TableHead>
              <TableHead className="w-[100px] m-2 p-2">Lectura</TableHead>
              <TableHead className="w-[100px] m-2 p-2">Editar</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody className="m-2 p-2">
            <TableRow className="m-2 p-2">
              <TableCell className="m-2 p-2">
                <p>Informacion</p>
              </TableCell>
              <TableCell className="m-2 p-2">
                <Checkbox id="no-access-1" />
              </TableCell>
              <TableCell className="m-2 p-2">
                <Checkbox id="read-1" />
              </TableCell>
              <TableCell className="m-2 p-2">
                <Checkbox id="edit-1" />
              </TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </div>
      <div className="flex justify-end m-2 p-2">
        <button className="bg-black text-white rounded-lg px-4 py-2 mt-4">Guardar</button>
      </div>
    </div>
    )
  );
}
