/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/DPxZ3Ul9abm
 */
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function RegisterUsuariosInternos() {
  return (
    (<div className="bg-white p-8">
      <div className="border-b-2 border-blue-600 pb-4 mb-6">
        <h1 className="text-3xl font-bold text-center text-blue-800">MODULO 3-1 REGISTRO - ALTA DE PERSONAL</h1>
      </div>
      <div className="border-2 border-blue-600 p-4">
        <h2 className="text-2xl font-bold text-blue-800 mb-6">DATOS PERSONALES</h2>
        <div className="grid grid-cols-2 gap-8">
          <div>
            <div className="border-2 border-blue-600 p-4 mb-6">
              <h3 className="text-xl font-bold">Fotografía</h3>
              <div className="h-[200px] bg-gray-200 mt-4" />
            </div>
            <div className="mb-4">
              <label className="block mb-1 font-bold">ENTIDAD EMPRESA</label>
              <Select>
                <SelectTrigger id="empresa">
                  <SelectValue placeholder="Seleccione una" />
                </SelectTrigger>
                <SelectContent position="popper">
                  <SelectItem value="ejemplo">Ejemplo, S.A.</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="mb-4">
              <label className="block mb-1 font-bold">Correo Electrónico (e-Mail)</label>
              <Input placeholder="juan@ejemplo@gmail.com" />
            </div>
            <div className="mb-4">
              <label className="block mb-1 font-bold">Profesión Ocupación</label>
              <Input placeholder="Plaza Solicitante:" />
            </div>
            <div className="grid grid-cols-3 gap-4">
              <div className="mb-4 col-span-2">
                <label className="block mb-1 font-bold">Dirección Completa</label>
                <Input placeholder="Calle - Avenida" />
              </div>
              <div className="mb-4">
                <label className="block mb-1 font-bold">Colonia</label>
                <Input />
              </div>
              <div className="mb-4">
                <label className="block mb-1 font-bold">Zona</label>
                <Input />
              </div>
              <div className="mb-4">
                <label className="block mb-1 font-bold">Departamento</label>
                <Input />
              </div>
              <div className="mb-4">
                <label className="block mb-1 font-bold">Municipio</label>
                <Input />
              </div>
            </div>
          </div>
          <div>
            <div className="mb-4">
              <label className="block mb-1 font-bold">CANDIDATO USUARIO</label>
              <Select>
                <SelectTrigger id="candidato">
                  <SelectValue placeholder="Seleccione uno" />
                </SelectTrigger>
                <SelectContent position="popper">
                  <SelectItem value="externo">Externo – Evaluado</SelectItem>
                  <SelectItem value="interno">Interno – Usuario</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div className="mb-4">
                <label className="block mb-1 font-bold">Primer Nombre</label>
                <Input />
              </div>
              <div className="mb-4">
                <label className="block mb-1 font-bold">Segundo Nombre</label>
                <Input />
              </div>
              <div className="mb-4">
                <label className="block mb-1 font-bold">Apellido Paterno</label>
                <Input />
              </div>
              <div className="mb-4">
                <label className="block mb-1 font-bold">Apellido Materno</label>
                <Input />
              </div>
            </div>
            <div className="grid grid-cols-3 gap-4">
              <div className="mb-4 col-span-2">
                <label className="block mb-1 font-bold">Fecha Nacimiento</label>
                <div className="flex">
                  <Input className="mr-2" placeholder="DD" />
                  <span>/</span>
                  <Input className="mx-2" placeholder="MM" />
                  <span>/</span>
                  <Input className="ml-2" placeholder="AAAA" />
                </div>
              </div>
              <div className="mb-4">
                <label className="block mb-1 font-bold">DPI CUI</label>
                <Input />
              </div>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div className="mb-4">
                <label className="block mb-1 font-bold">Lugar de Nacimiento</label>
                <Select>
                  <SelectTrigger id="nacimiento">
                    <SelectValue placeholder="Seleccione uno" />
                  </SelectTrigger>
                  <SelectContent position="popper">
                    <SelectItem value="guatemala">Guatemala</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="mb-4">
                <label className="block mb-1 font-bold">País de Origen</label>
                <Select>
                  <SelectTrigger id="origen">
                    <SelectValue placeholder="Seleccione uno" />
                  </SelectTrigger>
                  <SelectContent position="popper">
                    <SelectItem value="guatemala">Guatemala</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="mb-4">
                <label className="block mb-1 font-bold">Pasaporte Número</label>
                <Input />
              </div>
              <div className="mb-4">
                <label className="block mb-1 font-bold">Teléfono Casa</label>
                <Input />
              </div>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div className="mb-4">
                <label className="block mb-1 font-bold">Estado Civil</label>
                <Select>
                  <SelectTrigger id="civil">
                    <SelectValue placeholder="Seleccione uno" />
                  </SelectTrigger>
                  <SelectContent position="popper">
                    <SelectItem value="soltero">Soltero</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="mb-4">
                <label className="block mb-1 font-bold">Género</label>
                <Select>
                  <SelectTrigger id="genero">
                    <SelectValue placeholder="Seleccione uno" />
                  </SelectTrigger>
                  <SelectContent position="popper">
                    <SelectItem value="masculino">Masculino</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="mb-4">
                <label className="block mb-1 font-bold">Teléfono Móvil-Celular</label>
                <Input />
              </div>
            </div>
          </div>
        </div>
        <div className="flex items-center mt-6">
          <input className="mr-2" id="privacy" type="checkbox" />
          <label className="font-bold" htmlFor="privacy">
            He leído y acepto el aviso de privacidad
          </label>
        </div>
        <div className="flex justify-end mt-6">
          <Button>Guardar</Button>
        </div>
      </div>
    </div>)
  );
}
