/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Tp6TAp6ytYx
 */
import Link from "next/link"
import { DropdownMenuTrigger, DropdownMenuItem, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Checkbox } from "@/components/ui/checkbox"

export function RegistroInterno() {
  return (
    (
        <main className="p-8 space-y-8 mt-8 mb-8 mx-auto max-w-7xl">
          <h1 className="text-4xl font-bold mb-6 text-center text-blue-400">MODULO 3-1 REGISTRO - ALTA DE PERSONAL</h1>
          <h2 className="text-3xl font-semibold mb-4 text-center text-blue-300">DATOS PERSONALES</h2>
          <div className="flex items-center gap-6 mb-4">
            <div className="w-40 h-40 bg-gray-300 rounded">
              <img
                alt="User Photo"
                className="w-full h-full object-cover rounded"
                height="160"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "320/160",
                  objectFit: "cover",
                }}
                width="320" />
            </div>
            <div className="flex flex-col gap-4 w-full">
              <label className="flex flex-col gap-2">
                <span className="text-lg font-semibold">ENTIDAD EMPRESA</span>
                <select className="border rounded p-2">
                  <option>Ejemplo, S.A.</option>
                </select>
              </label>
              <label className="flex flex-col gap-2">
                <span className="text-lg font-semibold">CANDIDATO USUARIO</span>
                <select className="border rounded p-2">
                  <option>Externo – Evaluado</option>
                  <option>Interno – Usuario</option>
                </select>
              </label>
              <label className="flex flex-col gap-2">
                <span className="text-lg font-semibold">Correo Electrónico (e-Mail)</span>
                <Input
                  className="border rounded p-2"
                  placeholder="juan@ejemplo.com"
                  type="email" />
              </label>
            </div>
          </div>
          <div className="grid grid-cols-2 gap-4">
            <label className="flex flex-col gap-2">
              <span className="text-lg font-semibold">Dirección Completa</span>
              <Input className="border rounded p-2" placeholder="Calle - Avenida" type="text" />
            </label>
            <label className="flex flex-col gap-2">
              <span className="text-lg font-semibold">Colonia</span>
              <Input className="border rounded p-2" type="text" />
            </label>
            <label className="flex flex-col gap-2">
              <span className="text-lg font-semibold">Zona</span>
              <Input className="border rounded p-2" type="text" />
            </label>
            <label className="flex flex-col gap-2">
              <span className="text-lg font-semibold">Departamento</span>
              <Input className="border rounded p-2" type="text" />
            </label>
            <label className="flex flex-col gap-2">
              <span className="text-lg font-semibold">Municipio</span>
              <Input className="border rounded p-2" type="text" />
            </label>
            <label className="flex flex-col gap-2">
              <span className="text-lg font-semibold">País de Origen</span>
              <select className="border rounded p-2">
                <option>Guatemala</option>
              </select>
            </label>
          </div>
          <div className="grid grid-cols-2 gap-6">
            <label className="flex flex-col gap-2">
              <span className="text-lg font-semibold">Primer Nombre</span>
              <Input className="border rounded p-2" type="text" />
            </label>
            <label className="flex flex-col gap-2">
              <span className="text-lg font-semibold">Segundo Nombre</span>
              <Input className="border rounded p-2" type="text" />
            </label>
            <label className="flex flex-col gap-2">
              <span className="text-lg font-semibold">Apellido Paterno</span>
              <Input className="border rounded p-2" type="text" />
            </label>
            <label className="flex flex-col gap-2">
              <span className="text-lg font-semibold">Apellido Materno</span>
              <Input className="border rounded p-2" type="text" />
            </label>
          </div>
          <div className="flex gap-6">
            <label className="flex flex-col gap-2 w-full">
              <span className="text-lg font-semibold">Fecha Nacimiento</span>
              <div className="flex gap-4 w-full">
                <Input className="border rounded p-2" placeholder="DD" type="number" />
                <Input className="border rounded p-2" placeholder="MM" type="number" />
                <Input className="border rounded p-2" placeholder="AAAA" type="number" />
              </div>
            </label>
          </div>
          <div className="grid grid-cols-2 gap-6">
            <label className="flex flex-col gap-2">
              <span className="text-lg font-semibold">DPI CUI</span>
              <Input className="border rounded p-2" type="text" />
            </label>
            <label className="flex flex-col gap-2">
              <span className="text-lg font-semibold">Lugar de Nacimiento</span>
              <select className="border rounded p-2">
                <option>Guatemala</option>
              </select>
            </label>
            <label className="flex flex-col gap-2">
              <span className="text-lg font-semibold">Profesión Ocupación</span>
              <Input
                className="border rounded p-2"
                placeholder="Plaza Solicitante:"
                type="text" />
            </label>
            <label className="flex flex-col gap-2">
              <span className="text-lg font-semibold">Pasaporte Número</span>
              <Input className="border rounded p-2" type="text" />
            </label>
            <label className="flex flex-col gap-2">
              <span className="text-lg font-semibold">Teléfono Casa</span>
              <Input className="border rounded p-2" type="text" />
            </label>
            <label className="flex flex-col gap-2">
              <span className="text-lg font-semibold">Estado Civil</span>
              <select className="border rounded p-2">
                <option>Soltero</option>
              </select>
            </label>
            <label className="flex flex-col gap-2">
              <span className="text-lg font-semibold">Género</span>
              <select className="border rounded p-2">
                <option>Masculino</option>
              </select>
            </label>
            <label className="flex flex-col gap-2">
              <span className="text-lg font-semibold">Teléfono Móvil-Celular</span>
              <Input className="border rounded p-2" type="text" />
            </label>
          </div>
          <div className="flex items-center gap-2 mt-4">
            <Checkbox id="privacy" />
            <label className="text-lg font-semibold" htmlFor="privacy">
              He leído y acepto el aviso de privacidad
            </label>
          </div>
          <Button className="mt-4">Guardar</Button>
        </main>)
  );
}


function LockIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="18" height="11" x="3" y="11" rx="2" ry="2" />
      <path d="M7 11V7a5 5 0 0 1 10 0v4" />
    </svg>)
  );
}


function ServerIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="20" height="8" x="2" y="2" rx="2" ry="2" />
      <rect width="20" height="8" x="2" y="14" rx="2" ry="2" />
      <line x1="6" x2="6.01" y1="6" y2="6" />
      <line x1="6" x2="6.01" y1="18" y2="18" />
    </svg>)
  );
}


function FileQuestionIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z" />
      <path
        d="M10 10.3c.2-.4.5-.8.9-1a2.1 2.1 0 0 1 2.6.4c.3.4.5.8.5 1.3 0 1.3-2 2-2 2" />
      <path d="M12 17h.01" />
    </svg>)
  );
}


function FileIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z" />
      <polyline points="14 2 14 8 20 8" />
    </svg>)
  );
}


function CopyrightIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" />
      <path d="M15 9.354a4 4 0 1 0 0 5.292" />
    </svg>)
  );
}


function SettingsIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
      <circle cx="12" cy="12" r="3" />
    </svg>)
  );
}
