/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Bhsc2XzjjGY
 */
import { SelectValue, SelectTrigger, SelectLabel, SelectItem, SelectGroup, SelectContent, Select } from "@/components/ui/select"

export function selector() {
  return (
    (<Select>
      <SelectTrigger className="w-[180px]">
        <SelectValue placeholder="Select a city" />
      </SelectTrigger>
      <SelectContent>
        <SelectGroup>
          <SelectLabel>Cities</SelectLabel>
          <SelectItem value="new-york">New York</SelectItem>
          <SelectItem value="los-angeles">Los Angeles</SelectItem>
          <SelectItem value="chicago">Chicago</SelectItem>
          <SelectItem value="houston">Houston</SelectItem>
          <SelectItem value="phoenix">Phoenix</SelectItem>
        </SelectGroup>
      </SelectContent>
    </Select>)
  );
}
