name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.11.0' # Usa la versión de Node.js que prefieras

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to Server
      run: |
        echo "$DEPLOY_KEY" > deploy_key
        chmod 600 deploy_key
        scp -o StrictHostKeyChecking=no -i deploy_key -r .next/* root@172.16.5.55:/var/www/
        ssh -o StrictHostKeyChecking=no -i deploy_key root@172.16.5.55 'chown -R www-data:www-data /var/www/*'
        rm -f deploy_key
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
